#!/bin/sh 
### BEGIN INIT INFO
# Provides:          bismark-active
# Required-Start:    hostname $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the bismark active measurements daemon.
# Description:       Start the bismark active measurements daemon.
### END INIT INFO

START=98

CRONFILE=/etc/cron.d/cron-bismark-active

start() {

  echo "Starting BISMark Active Measurements ..."
  if [ -x /usr/bin/bismark-measure-wrapper ]; then
        echo "* * * * * root /usr/bin/bismark-measure-wrapper >>/tmp/bismark-scripts.log 2>&1" >$CRONFILE
        chmod +x $CRONFILE
  fi
  #todo wait for log to be written
  echo "Done."

}

stop() {
    [ -f $CRONFILE ] && {
        rm -f $CRONFILE
	#todo kill running scripts
    }
}

restart() {
    stop
    start
}

status() {
    if [ -f $CRONFILE ]; then
      echo "BISMark Active Measurements is running."
    else
      echo "BISMark Active Measurements is stopped."
    fi
}


case "$1" in
  start)
        start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
	restart
        exit 3
        ;;
  stop)
        stop
        ;;
  status)
        status
        exit $?
        ;;
  *)   
        echo "Usage: bismark-active [start|stop|status|restart]" >&2
        exit 3
        ;;
esac
